version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ${DB_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: ferremax_testing
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}