version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ${DB_NAME}
    volumes:
      - ./etc/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mhp24/ferremax-api:1.0.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    container_name: ferremax_stage
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}